### ISSUE TITLE
Designer le ASE launcher 

### ISSUE THREAD

**Issue by MouhamadBilal** [MouhamadBilal/ase-launcher#6]
### TODO

- [x]  Passer en dark mode
- [x]  Agrandir les icone
- [x]  Link les jeux au launcher 
- [x]  Au bon niveau (relative path)
- [x]  Ajouter des Images pour les icone de jeux
- [x]  Changer la favicon par défaut du launcher
